services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
  elastic:
    image: elasticsearch:8.13.3
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata:/user/share/elasticsearch/data
      - ./bootstrapPassword.txt:/run/secrets/bootstrapPassword.txt
    environment:
      - ELASTIC_PASSWORD_FILE=/run/secrets/bootstrapPassword.txt
      - xpack.security.enabled=false
      - discovery.type=single-node
  kibana:
    image: kibana:8.13.3
    ports:
      - 5601:5601
volumes:
  esdata:
    driver: local
